Server:
  AppVersion: "1.0.0"
  Host: "0.0.0.0"
  Port: "8080"
  Timeout: 60s
  WithGenerator: false

Postgres:
  host: "postgres"
  port: "5432"
  user: "root"
  password: "root"
  DBName: "taskdb"
  sslMode: "disable"
  pgDriver: "pgx"

Generator:
  cntRow: 500
  cntFeature: 100
  cntTag: 100
  maxTagInRow: 5
  nameFile: "bannerData.csv"